### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by ghost** [domineyn/prj-rev-bwfs-dasmoto#6]
https://github.com/domineyn/prj-rev-bwfs-dasmoto/blob/master/DamosArtsandCrafts/Resources/style.css#L24-L39

There's a lot of repetition here. Use classes to group equivalent sections into groups, then use those class names as selectors so that you can easily apply the shared/common styles.

For example, since you've given the `div` tags a class of `item`, you could rewrite a lot of this code into a single CSS rule, like so:

```css
.item {
  font-size: 32px;
  font-weight: bold;
  color: white;
}
```

Then use the ID as selectors to apply the colors that need to be applied to elements individually, for example:

```css
#frames {
  background-color: lightcoral;
}
```

You should also not repeat the font-family in every single rule. Try putting that style into a single CSS rule with multiple selectors, so you only need to change the font in one place if you ever update your site's design.

```css
h1, h2, h3, p, strong {
  font-family: Helvetica;
}
